-- Create the visitors table
CREATE TABLE public.visitors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL,
    ip_address INET,
    user_agent TEXT,
    city TEXT,
    country TEXT,
    referrer TEXT,
    utm_source TEXT,
    utm_medium TEXT,
    utm_campaign TEXT,
    page_url TEXT,
    event_type VARCHAR(50) CHECK (event_type IN ('page_view', 'click', 'impression', 'form_submit')),
    element_selector TEXT,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- RLS for visitors table
ALTER TABLE public.visitors ENABLE ROW LEVEL SECURITY;

-- Allow service_role to have full access
CREATE POLICY "Allow service_role to manage visitors"
ON public.visitors FOR ALL
USING (true)
WITH CHECK (true);

-- Allow anonymous users to insert their own analytics data
CREATE POLICY "Allow anonymous insert for visitors"
ON public.visitors FOR INSERT
WITH CHECK (true);

-- Indexes for faster queries
CREATE INDEX idx_visitors_session_id ON public.visitors (session_id);
CREATE INDEX idx_visitors_timestamp ON public.visitors (timestamp);
CREATE INDEX idx_visitors_event_type ON public.visitors (event_type);
