-- Create the orders table
CREATE TABLE public.orders (
    id TEXT PRIMARY KEY,
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    customer_address TEXT,
    status TEXT NOT NULL DEFAULT 'CREATED' CHECK (status IN ('CREATED', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'FAILED', 'PENDING')),
    payment_status TEXT CHECK (payment_status IN ('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED')),
    custom_image_urls TEXT[], -- Added for customer images
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create the order_details table
CREATE TABLE public.order_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL UNIQUE REFERENCES public.orders(id) ON DELETE CASCADE,
    order_items JSONB,
    subtotal NUMERIC(10, 2) NOT NULL,
    shipping_cost NUMERIC(10, 2) NOT NULL DEFAULT 0,
    discount_amount NUMERIC(10, 2) DEFAULT 0,
    total_amount NUMERIC(10, 2) NOT NULL,
    advance_amount NUMERIC(10, 2) NOT NULL,
    remaining_amount NUMERIC(10, 2),
    coupon_code TEXT,
    transaction_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT total_amount_check CHECK (total_amount = subtotal + shipping_cost - discount_amount),
    CONSTRAINT remaining_amount_check CHECK (remaining_amount = total_amount - advance_amount)
);

-- RLS for orders table
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow service_role to manage orders" ON public.orders FOR ALL
    USING (true)
    WITH CHECK (true);

-- RLS for order_details table
ALTER TABLE public.order_details ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow service_role to manage order_details" ON public.order_details FOR ALL
    USING (true)
    WITH CHECK (true);

-- Indexes for faster lookups
CREATE INDEX idx_orders_customer_phone ON public.orders ("customer_phone");
CREATE INDEX idx_order_details_order_id ON public.order_details ("order_id");

-- Function to update the updated_at timestamp
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to automatically update updated_at on orders table
CREATE TRIGGER on_orders_update
BEFORE UPDATE ON public.orders
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();
